---
- name: clone zsh config
  git: repo=git://github.com/xuxiaodong/oh-my-zsh.git dest={{ base_dir }}/oh-my-zsh accept_hostkey=yes

- name: set attributes
  file: path={{ base_dir }}/oh-my-zsh state=directory owner={{ users[0] }} group=wheel recurse=yes

- name: create symbolic link
  file: src={{ base_dir }}/oh-my-zsh/{{ item.src }} dest={{ home_dir }}/{{ item.dest }} state=link owner={{ users[0] }} group=wheel
  with_items:
  - { src: "_zshrc", dest: ".zshrc" }
