---
- name: clone ~/bin
  git: repo=git://github.com/xuxiaodong/bin.git dest={{ base_dir }}/bin accept_hostkey=yes force=yes

- name: set attributes
  file: path={{ base_dir }}/bin state=directory owner={{ users[0] }} group=wheel recurse=yes

- name: create symbolic link
  file: src={{ base_dir }}/bin/{{ item }} dest={{ home_dir }}/bin/{{ item }} state=link owner={{ users[0] }} group=wheel
  with_items:
  - gittossh.sh
  - makeaur.sh
  - twomonitor.sh
  - uptime
  - vimpager
